version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: xpenzi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xpenzi
    ports:
      - "5432:5432"
    volumes:
      - xpenzi_pgdata:/var/lib/postgresql/data

volumes:
  xpenzi_pgdata: